### ISSUE TITLE
Add Google Analytics Link Event Tracking

### ISSUE THREAD

**Issue by rveitch** [openfcci/fcc-global-nav#6]
### Overview

Add Google Analytics link click event tracking to the "AreaVoices" home link and "channels" site links.
#### Checklist
- [ ] AreaVoices Logo
- [ ] Channel - areavoices.com
- [ ] Channel - northlandoutdoors.com
- [ ] Channel - bisonmedia.areavoices.com
- [ ] Channel - sayanythingblog.com
#### Mockups & Examples

| eventCategory | eventAction |
| --- | --- |
| Global Nav | areavoices.com |
| Global Nav | northlandoutdoors.com |
| Global Nav | bisonmedia.areavoices.com |
| Global Nav | sayanythingblog.com |

**Selectors**

``` css
#wp-admin-bar-av-logo a
#wp-admin-bar-areavoices a
#wp-admin-bar-northlandoutdoors a
#wp-admin-bar-sayanything a
#wp-admin-bar-bisonmedia a
```

**Test JS**

``` javascript
$('#wp-admin-bar-av-logo a').click(function() {
  ga('send', 'event', 'Global Nav - Test', 'click', 'Logo - areavoices.com');
});

$('#wp-admin-bar-areavoices a').click(function() {
  ga('send', 'event', 'Global Nav - Test', 'click', 'Channels - areavoices.com');
});

$('#wp-admin-bar-northlandoutdoors a').click(function() {
  ga('send', 'event', 'Global Nav - Test', 'click', 'Channels - northlandoutdoors.com');
});

$('#wp-admin-bar-sayanything a').click(function() {
  ga('send', 'event', 'Global Nav - Test', 'click', 'Channels - sayanythingblog.com');
});

$('#wp-admin-bar-bisonmedia a').click(function() {
  ga('send', 'event', 'Global Nav - Test', 'click', 'Channels - bisonmedia.areavoices.com');
});
```
### Reference
- [GIST - FCC GA Examples](https://gist.github.com/rveitch/129a91bb6804f5ea7921dec2896ee6b4)
- [Event Tracking](https://developers.google.com/analytics/devguides/collection/analyticsjs/events#overview)
